services:
    register:
        build:
            context: register
            dockerfile: Dockerfile
        volumes:
            - ./register/src:/app/src
        environment:
            PORT: 3000

    node:
        build:
            context: node
            dockerfile: Dockerfile
        depends_on:
            - register
        volumes:
            - ./node/src:/app/src
        environment:
            PORT: 3000
            REGISTRATION_HOST: register
            REGISTRATION_PORT: 3000

    nginx:
        image: nginx:1.21
        volumes:
            - ./.config/nginx:/etc/nginx
        ports:
            - 5000:80
        depends_on:
            - node
            